# Generated by Django 4.0.1 on 2022-01-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('available_quantity', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'inventories',
                'db_table': 'Inventory',
            },
        ),
    ]
